In [1]:
import torch
import numpy as np

In [2]:
y     = torch.Tensor([[1,0,0,1,0], [0,0,0,1,1]]).numpy()
y_hat = torch.Tensor([[1,1,0,1,0], [1,1,0,0,1]]).numpy()

In [3]:
y_hat_binary = (y_hat > 0.5).astype(int)
accuracy = np.mean(y_hat_binary == y)
accuracy

np.float64(0.6)

In [4]:
from sklearn.metrics import confusion_matrix

In [23]:
y_true = torch.Tensor([[1,0,0,1,0,0,0], [0,0,0,1,1,0,0]]).flatten()
y_pred = torch.Tensor([[1,1,0,1,0,0,1], [1,1,0,0,1,0,0]]).flatten()

print(y_true)
print(y_pred)

tensor([1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.])
tensor([1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0.])


In [24]:
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
print(tn, fp, fn, tp)

6 4 1 3


In [26]:
print(confusion_matrix(y_true, y_pred))
print('tn fp\nfn tp')

[[6 4]
 [1 3]]
tn fp
fn tp
